openapi: 3.0.3
info:
  title: Calendar API (Calendars + Events)
  description: API for a minimal Google-like calendar (calendars + events).
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local API server

tags:
  - name: Calendars
    description: User calendars (owned/shared)
  - name: Events
    description: Calendar events CRUD

paths:
  /calendars:
    get:
      tags: [Calendars]
      operationId: listCalendars
      security:
        - bearerAuth: []
      summary: List calendars
      description: Returns calendars owned by the user and calendars shared with the user.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Calendar'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
    post:
      tags: [Calendars]
      operationId: createCalendar
      security:
        - bearerAuth: []
      summary: Create calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  calendar:
                    $ref: '#/components/schemas/Calendar'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'

  /calendars/{calendarId}:
    parameters:
      - in: path
        name: calendarId
        required: true
        schema:
          type: integer
    get:
      tags: [Calendars]
      operationId: getCalendar
      security:
        - bearerAuth: []
      summary: Get calendar details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  calendar:
                    $ref: '#/components/schemas/Calendar'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    patch:
      tags: [Calendars]
      operationId: updateCalendar
      security:
        - bearerAuth: []
      summary: Update calendar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarUpdateRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  calendar:
                    $ref: '#/components/schemas/Calendar'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (insufficient role)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
    delete:
      tags: [Calendars]
      operationId: deleteCalendar
      security:
        - bearerAuth: []
      summary: Delete calendar
      description: Only the owner can delete a calendar.
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (not owner)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'

  /calendars/{calendarId}/events:
    parameters:
      - in: path
        name: calendarId
        required: true
        schema:
          type: integer
    get:
      tags: [Events]
      operationId: listEvents
      security:
        - bearerAuth: []
      summary: List events in time range
      parameters:
        - in: query
          name: from
          required: true
          schema:
            type: string
            format: date-time
          description: Inclusive range start (ISO 8601)
        - in: query
          name: to
          required: true
          schema:
            type: string
            format: date-time
          description: Exclusive range end (ISO 8601)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (no access to calendar)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found (calendar not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    post:
      tags: [Events]
      operationId: createEvent
      security:
        - bearerAuth: []
      summary: Create event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (viewer cannot create)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found (calendar not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'

  /events/{eventId}:
    parameters:
      - in: path
        name: eventId
        required: true
        schema:
          type: integer
    get:
      tags: [Events]
      operationId: getEvent
      security:
        - bearerAuth: []
      summary: Get event details
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (no access to calendar)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
    patch:
      tags: [Events]
      operationId: updateEvent
      security:
        - bearerAuth: []
      summary: Update event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventUpdate'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    $ref: '#/components/schemas/Event'
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (viewer cannot edit)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'
        '422':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error422'
    delete:
      tags: [Events]
      operationId: deleteEvent
      security:
        - bearerAuth: []
      summary: Delete event
      responses:
        '204':
          description: No Content
        '401':
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error401'
        '403':
          description: Forbidden (viewer cannot delete)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error403'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error404'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # --- Requests ---
    CalendarCreateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
        color:
          type: string
          nullable: true
      required: [name]

    CalendarUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
        color:
          type: string
          nullable: true

    EventCreate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        all_day:
          type: boolean
          default: false
        timezone:
          type: string
          default: Europe/Warsaw
        recurrence_rule:
          type: string
          nullable: true
          description: RFC5545 RRULE
      required: [title, starts_at, ends_at]

    EventUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        all_day:
          type: boolean
        timezone:
          type: string
        recurrence_rule:
          type: string
          nullable: true
        status:
          type: string
          enum: [confirmed, cancelled]

    # --- Responses / Entities ---
    Calendar:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        color:
          type: string
          nullable: true
        role:
          type: string
          description: Current user's role for this calendar
          enum: [owner, editor, viewer]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Event:
      type: object
      properties:
        id:
          type: integer
        calendar_id:
          type: integer
        title:
          type: string
        description:
          type: string
          nullable: true
        location:
          type: string
          nullable: true
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        all_day:
          type: boolean
        timezone:
          type: string
          example: Europe/Warsaw
        recurrence_rule:
          type: string
          nullable: true
          description: RFC5545 RRULE
        status:
          type: string
          enum: [confirmed, cancelled]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    # --- Errors ---
    Error401:
      type: object
      properties:
        message:
          type: string
          example: Unauthenticated.

    Error403:
      type: object
      properties:
        message:
          type: string
          example: Forbidden.

    Error404:
      type: object
      properties:
        message:
          type: string
          example: Not Found.

    Error422:
      type: object
      properties:
        message:
          type: string
          example: The given data was invalid.
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
